version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify the Node.js version suitable for your Angular project
    commands:
      - echo "Installing npm dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build tasks (e.g., linting, tests)..."
      # - npm test # Uncomment if you have tests to run
      # - npm run lint # Uncomment if you have linting to run

  build:
    commands:
      - echo "Building the Angular application for production..."
      - npm run build -- --configuration=production # Or ng build --configuration=production
      # If your project name is not the same as the default, you might need:
      # - npm run build -- --configuration=production --output-path=dist/your-project-name

  post_build:
    commands:
      - echo "Post-build tasks (e.g., zipping artifacts)..."

artifacts:
  files:
    - '**/*'
  base-directory: dist/emergency-dashboard # Replace <your-project-name> with your actual project name
  # If you have a different output path configured in angular.json, adjust base-directory accordingly.
  # For example, if your build outputs directly to 'dist', then use: base-directory: dist